# Generated by Django 3.0.4 on 2020-03-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('author', models.CharField(max_length=40, verbose_name='Author')),
                ('publisher', models.CharField(max_length=40, verbose_name='Publisher')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='book_images')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='books.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Language')),
            ],
        ),
    ]
