# Generated by Django 3.0.4 on 2020-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
