# Generated by Django 3.0.4 on 2020-05-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
