# Generated by Django 3.0.4 on 2020-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200503_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
